var data = {
"CS 100": "Freshman Orientation",
"CS 101": "Intro Computing: Engrg & Sci",
"CS 102": "Little Bits to Big Ideas",
"CS 105": "Intro Computing: Non-Tech",
"CS 125": "Intro to Computer Science",
"CS 173": "Discrete Structures",
"CS 196": "Freshman Honors",
"CS 199": "Undergraduate Open Seminar",
"CS 210": "Ethical & Professional Issues",
"CS 225": "Data Structures",
"CS 233": "Computer Architecture",
"CS 241": "System Programming",
"CS 242": "Programming Studio",
"CS 296": "Honors Course",
"CS 357": "Numerical Methods I",
"CS 373": "Theory of Computation",
"CS 397": "Individual Study",
"CS 398": "Special Topics",
"CS 410": "Text Information Systems",
"CS 411": "Database Systems",
"CS 412": "Introduction to Data Mining",
"CS 413": "Intro to Combinatorics",
"CS 414": "Multimedia Systems",
"CS 418": "Interactive Computer Graphics",
"CS 419": "Production Computer Graphics",
"CS 420": "Parallel Progrmg: Sci & Engrg",
"CS 421": "Progrmg Languages & Compilers",
"CS 422": "Programming Language Design",
"CS 423": "Operating Systems Design",
"CS 424": "Real-Time Systems",
"CS 425": "Distributed Systems",
"CS 426": "Compiler Construction",
"CS 427": "Software Engineering I",
"CS 428": "Software Engineering II",
"CS 429": "Software Engineering II, ACP",
"CS 431": "Embedded Systems",
"CS 433": "Computer System Organization",
"CS 436": "Computer Networking Laboratory",
"CS 438": "Communication Networks",
"CS 439": "Wireless Networks",
"CS 440": "Artificial Intelligence",
"CS 445": "Computational Photography",
"CS 446": "Machine Learning",
"CS 447": "Natural Language Processing",
"CS 450": "Numerical Analysis",
"CS 457": "Numerical Methods II",
"CS 460": "Security Laboratory",
"CS 461": "Computer Security I",
"CS 463": "Computer Security II",
"CS 465": "User Interface Design",
"CS 466": "Introduction to Bioinformatics",
"CS 467": "Social Visualization",
"CS 468": "Tech and Advertising Campaigns",
"CS 473": "Fundamental Algorithms",
"CS 475": "Formal Models of Computation",
"CS 476": "Program Verification",
"CS 477": "Formal Software Devel Methods",
"CS 481": "Stochastic Processes & Applic",
"CS 482": "Simulation",
"CS 483": "Applied Parallel Programming",
"CS 484": "Parallel Programming",
"CS 491": "Seminar",
"CS 492": "Senior Project I",
"CS 493": "Senior Project II, ACP",
"CS 494": "Senior Project II",
"CS 498": "Special Topics",
"CS 499": "Senior Thesis",
"CS 511": "Advanced Data Management",
"CS 512": "Data Mining Principles",
"CS 519": "Scientific Visualization",
"CS 522": "Programming Language Semantics",
"CS 523": "Advanced Operating Systems",
"CS 524": "Concurrent Progrmg Languages",
"CS 525": "Advanced Distributed Systems",
"CS 526": "Advanced Compiler Construction",
"CS 527": "Topics in Software Engineering",
"CS 528": "Obj-Oriented Progrmg & Design",
"CS 533": "Parallel Computer Architecture",
"CS 536": "Fault-Tolerant Dig Syst Design",
"CS 538": "Advanced Computer Networks",
"CS 541": "Computer Systems Analysis",
"CS 543": "Computer Vision",
"CS 544": "Optimiz in Computer Vision",
"CS 545": "Systems Modeling & Simulation",
"CS 546": "Machine Learning in NLP",
"CS 548": "Models of Cognitive Processes",
"CS 549": "Seminar in Cognitive Science",
"CS 554": "Parallel Numerical Algorithms",
"CS 555": "Numerical Methods for PDEs",
"CS 556": "Iterative & Multigrid Methods",
"CS 558": "Topics in Numerical Analysis",
"CS 563": "Advanced Computer Security",
"CS 565": "Human-Computer Interaction",
"CS 571": "Combinatorial Mathematics",
"CS 572": "Extremal Graph Theory",
"CS 573": "Algorithms",
"CS 574": "Randomized Algorithms",
"CS 575": "Methods of Combinatorics",
"CS 576": "Topics in Automated Deduction",
"CS 579": "Computational Complexity",
"CS 583": "Approximation Algorithms",
"CS 584": "Embedded System Verification",
"CS 591": "Advanced Seminar",
"CS 597": "Individual Study",
"CS 598": "Special Topics",
"CS 599": "Thesis Research"};
